### ISSUE TITLE
Licenseについて

### ISSUE THREAD

**Issue by Jerome-1010** [nokamoto/print-github-contrib#8]
KADOKAWA Connectedさんのエンジニアブログの記事 https://engineering.kdx.co.jp/entry/2020/08/06/163000 を見て自分も是非使わせていただきたいと思ったのですが、もし良ければLicense表記を追加いただけないでしょうか？

**Comment by nokamoto** [comment]
はい、追加します。

**Comment by nokamoto** [comment]
追加してみました。

**Comment by Jerome-1010** [comment]
ありがとうございます！！
